if (WIN32)
    set(AVF_WIN32 TRUE)
elseif (UNIX)
    set(AVF_UNIX TRUE)
    if (CMAKE_SYSTEM_NAME MATCHES "Linux")
        set(AVF_LINUX TRUE)
    elseif (MAKE_SYSTEM_NAME MATCHES "Android")
        set(AVF_ANDROID TRUE)
    elseif (MAKE_SYSTEM_NAME MATCHES "Darwin")
        set(AVF_MACOS TRUE)
    endif ()
elseif (APPLE)
    set(AVF_APPLE TRUE)
else ()

endif ()